from sqlalchemy import types

data_types = {
	'id': types.CHAR(32),
    'acao': types.VARCHAR(300),
    'cnae': types.VARCHAR(300),
    'Classificacao_Idade': types.VARCHAR(50),
    'escolaridade': types.VARCHAR(300),
    'iniciativa': types.VARCHAR(300),
    'instrumento': types.VARCHAR(300),
    'setor': types.VARCHAR(300),
    'sexo': types.VARCHAR(50),
    'cnpj': types.VARCHAR(20),
    'tipo_publico': types.VARCHAR(300),
    'data_atendimento': types.DATETIME,
    'tema': types.VARCHAR(300),
    'tipo_iniciativa': types.VARCHAR(300),
    'municio_cliente_atendido': types.VARCHAR(300),
    'cod_municipio_pf': types.BIGINT,
    'cod_municipio_pj': types.BIGINT,
    'cnae_principal': types.VARCHAR(300),
    'segmento_publico_alvo': types.VARCHAR(300),
    'aplicacao_instrumento': types.VARCHAR(100),
    'cod_dap': types.VARCHAR(255),
    'nirf': types.VARCHAR(255),
    'tipo_empreendimento': types.VARCHAR(100),
    'produto': types.VARCHAR(250),
    'unidade_organizacional': types.VARCHAR(250),
    'NuAtendimentosExecutado': types.INTEGER,
    'SkClientePessoaFisicaAtendida': types.BIGINT,
}