table _Medidas
	lineageTag: 915f8f46-b90a-4597-91b7-df471c4b68da

	measure 'Barra Progresso - NO PAÍS' = ```
			
			
			
			VAR vValor =            
			    [Posição no País] 
			
			VAR vValor_formatado =      
			    FORMAT( vValor, "0" ) 
			
			VAR vMeta =            
			    [% Posição no País]
			
			--------------------------------
			-- FORMATAÇÕES   
			--------------------------------
			
			VAR vFonte = "Cambria "
			
			VAR vRotulo_categoria_texto = [Município] & " - " & FORMAT( [Posição no País], "0")
			/*VAR vRotulo_categoria_texto = [Município]"Rank Atual: "*/
			VAR vRotulo_categoria_cor = "#0075A2"
			VAR vRotulo_categoria_tam = 12
			
			
			VAR vRotulo_dados_cor = "withe"
			VAR vRotulo_dados_tam = 12
			VAR vRotulo_dados_peso = 650
			VAR vRotulo_dados_posicao = 65
			
			
			VAR vBarra_altura = 10
			
			VAR vBarra_progresso_cor = "#0075A2"
			
			VAR vBarra_fundo_cor = "#0075A2"
			VAR vBarra_fundo_opacidade = 9
			
			VAR vLinha_meta_larg = 3
			VAR vLinha_meta_cor = "#3f3f3f"
			
			
			
			
			
			RETURN 
			
			"data:image/svg+xml;utf8,<svg width='200' height='70' viewBox='0 0 200 70' fill='none' xmlns='http://www.w3.org/2000/svg'><rect id='f001' x='0' y='37' width='190' height='" & vBarra_altura & "' fill='" & vBarra_fundo_cor & "'
			opacity='0." & vBarra_fundo_opacidade& "' /><rect id='f002' x='0' y='37' width='" & MIN( 190,  MAX( 0, ROUND( 131 * vValor, 0 ) ) )  & "' height='" & vBarra_altura & "' fill='" & vBarra_progresso_cor & "' /><text id='f003' fill='" & vRotulo_categoria_cor & "' font-family='" & vFonte & "' font-size='" & vRotulo_categoria_tam & "' font-weight='400'><tspan x='0' y='28'> " & vRotulo_categoria_texto & "</tspan></text><text id='f004' fill='" & vRotulo_dados_cor& "' font-family='" & vFonte & "' font-size='" & vRotulo_dados_tam & "' font-weight='" & vRotulo_dados_peso & "'><tspan x='" & vRotulo_dados_posicao & "' y='28'>" & vValor_formatado & "</tspan></text><rect id='f005' x='" & MIN( 190,  MAX( 0, ROUND( 131 * vMeta , 0 ) ) )  & " ' y='32' width='" & vLinha_meta_larg & "' height='" & vBarra_altura + 10 & "' fill='" & vLinha_meta_cor & "' /></svg>"
			```
		displayFolder: Barra de progresso - População
		lineageTag: 7bba3073-f3ed-43c5-a218-6e53cbfba6e0

	measure Município = SELECTEDVALUE(municipio[municipio])
		displayFolder: Barra de progresso - População
		lineageTag: d9d4ca15-48d9-4d11-8f92-f75dca9e7ef6

	measure 'No pais' = SUM('Barra de Progresso'[No País])
		formatString: #,0
		displayFolder: Barra de progresso - População
		lineageTag: 3daa87ec-a5f6-41c3-b222-a9a3a6631d2e

	measure 'Barra Progresso - No Estado' = ```
			
			
			
			VAR vValor =            
			    [Posição no Estado] 
			
			VAR vValor_formatado =      
			    FORMAT( vValor, "0" ) 
			
			VAR vMeta =            
			    [% Posição no Estado]
			
			--------------------------------
			-- FORMATAÇÕES   
			--------------------------------
			
			VAR vFonte = "Cambria "
			
			VAR vRotulo_categoria_texto = [Município] & " - " & FORMAT( [Posição no Estado], "0")
			/*VAR vRotulo_categoria_texto = [Município]"Rank Atual: "*/
			VAR vRotulo_categoria_cor = "#0075A2"
			VAR vRotulo_categoria_tam = 12
			
			
			VAR vRotulo_dados_cor = "withe"
			VAR vRotulo_dados_tam = 12
			VAR vRotulo_dados_peso = 650
			VAR vRotulo_dados_posicao = 65
			
			
			VAR vBarra_altura = 10
			
			VAR vBarra_progresso_cor = "#0075A2"
			
			VAR vBarra_fundo_cor = "#0075A2"
			VAR vBarra_fundo_opacidade = 9
			
			VAR vLinha_meta_larg = 3
			VAR vLinha_meta_cor = "#3f3f3f"
			
			
			
			
			
			RETURN 
			
			"data:image/svg+xml;utf8,<svg width='200' height='70' viewBox='0 0 200 70' fill='none' xmlns='http://www.w3.org/2000/svg'><rect id='f001' x='0' y='37' width='190' height='" & vBarra_altura & "' fill='" & vBarra_fundo_cor & "'
			opacity='0." & vBarra_fundo_opacidade& "' /><rect id='f002' x='0' y='37' width='" & MIN( 190,  MAX( 0, ROUND( 131 * vValor, 0 ) ) )  & "' height='" & vBarra_altura & "' fill='" & vBarra_progresso_cor & "' /><text id='f003' fill='" & vRotulo_categoria_cor & "' font-family='" & vFonte & "' font-size='" & vRotulo_categoria_tam & "' font-weight='400'><tspan x='0' y='28'> " & vRotulo_categoria_texto & "</tspan></text><text id='f004' fill='" & vRotulo_dados_cor& "' font-family='" & vFonte & "' font-size='" & vRotulo_dados_tam & "' font-weight='" & vRotulo_dados_peso & "'><tspan x='" & vRotulo_dados_posicao & "' y='28'>" & vValor_formatado & "</tspan></text><rect id='f005' x='" & MIN( 190,  MAX( 0, ROUND( 131 * vMeta , 0 ) ) )  & " ' y='32' width='" & vLinha_meta_larg & "' height='" & vBarra_altura + 10 & "' fill='" & vLinha_meta_cor & "' /></svg>"
			```
		displayFolder: Barra de progresso - População
		lineageTag: 93a054e8-0b45-427e-ba2d-89443a50c2b6

	measure 'Posição no Estado' = SUM(pop_residente_2022[posicao_estadual_populacional])
		formatString: 0
		displayFolder: Barra de progresso - População
		lineageTag: 15a506bb-0b20-4dc0-85bc-f267346bf74d

	measure 'Posição no País' = SELECTEDVALUE(pop_residente_2022[posicao_nacional_populacional])
		formatString: 0
		displayFolder: Barra de progresso - População
		lineageTag: 2d01ab31-944f-4a8a-be18-aec78bfa6191

	measure Texto1 = "Comparando a outros municípios"
		lineageTag: 9933f504-2695-4cf6-8233-b27906786913

	measure '% Posição no Estado' =
			
			DIVIDE([Posição no Estado], [No Estado])
		displayFolder: Barra de progresso - População
		lineageTag: fcb74ddf-1325-4b63-99cb-c69565f909f0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'No Estado' = SELECTEDVALUE('Barra de Progresso'[No Estado])
		formatString: 0
		displayFolder: Barra de progresso - População
		lineageTag: 15b62098-720d-47cf-a141-cfdc48573066

	measure 'Densidade Demográfica' = ```
			
			"Densidade demográfica censo 2022: " & 
			FORMAT(SELECTEDVALUE(densidade_demografica[densidade_demografica]), "0.00")
			```
		lineageTag: 3fc20179-e3a1-4e88-8b49-27800fe2fd2f

	column Column1
		dataType: string
		isHidden
		lineageTag: c39abb20-cbf4-4146-97ff-b8c10d10312b
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition _Medidas = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

