table densidade_demografica
	lineageTag: 74716fde-ee87-40e2-876c-7e2f1058c2ef

	measure 'Densidade Demográfica' = ```
			
			"Densidade demográfica censo 2022: " & 
			FORMAT(SELECTEDVALUE(densidade_demografica[densidade_demografica]), "0.00")
			```
		displayFolder: Medidas
		lineageTag: 3fc20179-e3a1-4e88-8b49-27800fe2fd2f

	column code_muni
		dataType: string
		displayFolder: Colunas
		lineageTag: 6581cd83-30aa-41bb-9a15-54449cbf9d6e
		summarizeBy: none
		sourceColumn: code_muni

		annotation SummarizationSetBy = Automatic

	column densidade_demografica
		dataType: double
		displayFolder: Colunas
		lineageTag: 12f9c94b-d5b4-4424-a109-4f285f0e5839
		summarizeBy: sum
		sourceColumn: densidade_demografica

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition densidade_demografica = m
		mode: import
		source =
				let
				    Source = Sql.Database("10.11.4.21", "dw_uim"),
				    dbo_densidade_demografica = Source{[Schema="dbo",Item="densidade_demografica"]}[Data]
				in
				    dbo_densidade_demografica

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

